const data = [
  {
    price: 2000,
    name: "Palm Harbour",
    address: "123 Main St, New York",
    imgId : 1,
    type : "House",
    popular: true,
    info: {
      beds: 3,
      bathrooms: 2,
      area: "5 x 7 ",
    },
  },
  {
    price: 1800,
    name: "Willow Haven",
    address: "456 Elm St, New York",
    imgId : 2,
    type : "House",
    popular: true,
    info: {
      beds: 4,
      bathrooms: 3,
      area: "8 x 10 ",
    },
  },
  {
    price: 1500,
    name: "Misty Meadows",
    address: "789 Oak St, Delhi",
    imgId : 3,
    type : "House",
    popular: true,
    info: {
      beds: 2,
      bathrooms: 1,
      area: "6 x 9 ",
    },
  },
  {
    price: 1200,
    name: "Golden Glade",
    address: "101 Pine St, Delhi",
    imgId : 4,
    type : "House",
    popular: true,
    info: {
      beds: 3,
      bathrooms: 2,
      area: "7 x 10 ",
    },
  },
  {
    price: 2500,
    name: "Ocean Breeze",
    address: "222 Palm St, Mumbai",
    imgId : 5,
    type : "House",
    popular: false,
    info: {
      beds: 4,
      bathrooms: 3,
      area: "6 x 8 ",
    },
  },
  {
    price: 2800,
    name: "Sunset View",
    address: "333 Maple St, Mumbai",
    imgId : 6,
    type : "House",
    popular: false,
    info: {
      beds: 5,
      bathrooms: 4,
      area: "8 x 12 ",
    },
  },
  {
    price: 3000,
    name: "Hillside Retreat",
    address: "444 Birch St, California",
    imgId : 7,
    type : "House",
    popular: false,
    info: {
      beds: 3,
      bathrooms: 2,
      area: "7 x 9 ",
    },
  },
  {
    price: 3200,
    name: "Riverfront Oasis",
    address: "555 Cedar St, California",
    imgId : 8,
    type : "House",
    popular: false,
    info: {
      beds: 4,
      bathrooms: 3,
      area: "8 x 10 ",
    },
  },
  {
    price: 2800,
    name: "Mountain Vista",
    address: "666 Redwood St, California",
    imgId : 9,
    type : "House",
    popular: false,
    info: {
      beds: 3,
      bathrooms: 2,
      area: "7 x 8 ",
    },
  },
  {
    price: 3000,
    name: "Glory Building",
    address: "666 Redwood St, Delhi",
    imgId : 10,
    type : "Flat",
    popular: false,
    info: {
      beds: 2,
      bathrooms: 1,
      area: "9 x 8 ",
    },
  },

];
export default data;